import matplotlib
import matplotlib.pyplot as plt
import io
import pywebio


def draw_graph(weather_data):
    """ Draws a graph based on the inputted weather data """
    matplotlib.use('agg')
    times, temps, feel_temps, pressures, humids = weather_data

    # v nasledujici casti by slo nektere casti kodu prepsat do samostatne fce, ale bohuzel nam na to nezbyl cas :(
    # osa x bohuzel ma rozbite formatovani - zkouseli jsme opravit, ale narazili jsme na limitace PyWebIO... vysvetlime a ukazeme behem obhajoby

    if temps and not feel_temps and not pressures and not humids:
        fig, ax = plt.subplots()
        ax.plot(times, temps, label="Teplota (C)")
        fig.legend(loc='upper left')
        ax.set_xlabel('Čas (h)')
        buf = io.BytesIO()
        fig.savefig(buf)
        pywebio.output.put_image(buf.getvalue())
    elif feel_temps and not temps and not pressures and not humids:
        fig, ax = plt.subplots()
        ax.plot(times, feel_temps, label="Pocitová teplota (C)")
        fig.legend(loc='upper left')
        ax.set_xlabel('Čas (h)')
        buf = io.BytesIO()
        fig.savefig(buf)
        pywebio.output.put_image(buf.getvalue())
    elif pressures and not feel_temps and not temps and not humids:
        fig, ax = plt.subplots()
        ax.plot(times, pressures, label="Tlak (hPa)")
        fig.legend(loc='upper left')
        ax.set_xlabel('Čas (h)')
        buf = io.BytesIO()
        fig.savefig(buf)
        pywebio.output.put_image(buf.getvalue())
    elif humids and not feel_temps and not pressures and not temps:
        fig, ax = plt.subplots()
        ax.plot(times, humids, label="Vlhkost (%)")
        fig.legend(loc='upper left')
        ax.set_xlabel('Čas (h)')
        buf = io.BytesIO()
        fig.savefig(buf)
        pywebio.output.put_image(buf.getvalue())
    elif temps and feel_temps and not pressures and not humids:
        fig, ax = plt.subplots()
        ax.plot(times, temps, label="Teplota (C)")
        ax.plot(times, feel_temps, label='Pocitová teplota (C)')
        fig.legend(loc='upper left')
        ax.set_xlabel('Čas (h)')
        buf = io.BytesIO()
        fig.savefig(buf)
        pywebio.output.put_image(buf.getvalue())
    elif temps and pressures and not feel_temps and not humids:
        fig, ax = plt.subplots()
        ax.plot(times, temps, label="Teplota (C)")
        ax.plot(times, pressures, label='Tlak (hPa)')
        fig.legend(loc='upper left')
        ax.set_xlabel('Čas (h)')
        buf = io.BytesIO()
        fig.savefig(buf)
        pywebio.output.put_image(buf.getvalue())
    elif temps and humids and not feel_temps and not pressures:
        fig, ax = plt.subplots()
        fig2, ax2 = plt.subplots()
        ax.plot(times, temps, label="Teplota (C)")
        ax2.plot(times, humids, label='Vlhkosti (%)')
        fig.legend(loc='upper left')
        ax.set_xlabel('Čas (h)')
        buf = io.BytesIO()
        fig.savefig(buf)

        pywebio.output.put_image(buf.getvalue())
        fig2.legend(loc='upper left')
        ax2.set_xlabel('Čas (h)')
        buf2 = io.BytesIO()
        fig2.savefig(buf2)
        pywebio.output.put_image(buf2.getvalue())
    elif feel_temps and pressures and not temps and not humids:
        fig, ax = plt.subplots()
        fig2, ax2 = plt.subplots()
        ax.plot(times, feel_temps, label="Pocitová teplota (C)")
        ax2.plot(times, pressures, label='Tlak (hPa)')
        fig.legend(loc='upper left')
        ax.set_xlabel('Čas (h)')
        buf = io.BytesIO()
        fig.savefig(buf)
        pywebio.output.put_image(buf.getvalue())

        fig2.legend(loc='upper left')
        ax2.set_xlabel('Čas (h)')
        buf2 = io.BytesIO()
        fig2.savefig(buf2)
        pywebio.output.put_image(buf2.getvalue())
    elif feel_temps and humids and not temps and not pressures:
        fig, ax = plt.subplots()
        fig2, ax2 = plt.subplots()
        ax.plot(times, feel_temps, label="Pocitová teplota (C)")
        ax2.plot(times, humids, label='Vlhkosti (%)')
        fig.legend(loc='upper left')
        ax.set_xlabel('Čas (h)')
        buf = io.BytesIO()
        fig.savefig(buf)
        pywebio.output.put_image(buf.getvalue())

        fig2.legend(loc='upper left')
        ax2.set_xlabel('Čas (h)')
        buf2 = io.BytesIO()
        fig2.savefig(buf2)
        pywebio.output.put_image(buf2.getvalue())
    elif pressures and humids and not temps and not feel_temps:
        fig, ax = plt.subplots()
        fig2, ax2 = plt.subplots()
        ax.plot(times, pressures, label="Tlak (hPa)")
        ax2.plot(times, humids, label='Vlhkosti (%)')
        fig.legend(loc='upper left')
        ax.set_xlabel('Čas (h)')
        buf = io.BytesIO()
        fig.savefig(buf)
        pywebio.output.put_image(buf.getvalue())

        fig2.legend(loc='upper left')
        ax2.set_xlabel('Čas (h)')
        buf2 = io.BytesIO()
        fig2.savefig(buf2)
        pywebio.output.put_image(buf2.getvalue())
    elif temps and feel_temps and pressures and not humids:
        fig, ax = plt.subplots()
        fig2, ax2 = plt.subplots()
        ax.plot(times, temps, label="Teplota (C)")
        ax.plot(times, feel_temps, label='Pocitová teplota (C)')
        ax2.plot(times, pressures, label='Tlak (hPa)')
        fig.legend(loc='upper left')
        ax.set_xlabel('Čas (h)')
        buf = io.BytesIO()
        fig.savefig(buf)
        pywebio.output.put_image(buf.getvalue())

        fig2.legend(loc='upper left')
        ax2.set_xlabel('Čas (h)')
        buf2 = io.BytesIO()
        fig2.savefig(buf2)
        pywebio.output.put_image(buf2.getvalue())
    elif temps and feel_temps and humids and not pressures:
        fig, ax = plt.subplots()
        fig2, ax2 = plt.subplots()
        ax.plot(times, temps, label="Teplota (C)")
        ax.plot(times, feel_temps, label='Pocitová teplota (C)')
        ax2.plot(times, humids, label='Vlhkosti (%)')
        fig.legend(loc='upper left')
        ax.set_xlabel('Čas (h)')
        buf = io.BytesIO()
        fig.savefig(buf)
        pywebio.output.put_image(buf.getvalue())

        fig2.legend(loc='upper left')
        ax2.set_xlabel('Čas (h)')
        buf2 = io.BytesIO()
        fig2.savefig(buf2)
        pywebio.output.put_image(buf2.getvalue())
    elif temps and pressures and humids and not feel_temps:
        fig, ax = plt.subplots()
        fig2, ax2 = plt.subplots()
        fig3, ax3 = plt.subplots()
        ax.plot(times, temps, label="Teplota (C)")
        ax2.plot(times, pressures, label='Tlak (hPa)')
        ax3.plot(times, humids, label='Vlhkosti (%)')
        fig.legend(loc='upper left')
        ax.set_xlabel('Čas (h)')
        buf = io.BytesIO()
        fig.savefig(buf)
        pywebio.output.put_image(buf.getvalue())

        fig2.legend(loc='upper left')
        ax2.set_xlabel('Čas (h)')
        buf2 = io.BytesIO()
        fig2.savefig(buf2)
        pywebio.output.put_image(buf2.getvalue())

        fig3.legend(loc='upper left')
        ax3.set_xlabel('Čas (h)')
        buf3 = io.BytesIO()
        fig3.savefig(buf3)
        pywebio.output.put_image(buf3.getvalue())
    elif feel_temps and pressures and humids and not temps:
        fig, ax = plt.subplots()
        fig2, ax2 = plt.subplots()
        fig3, ax3 = plt.subplots()
        ax.plot(times, feel_temps, label="Pocitová teplota (C)")
        ax2.plot(times, pressures, label='Tlak (hPa)')
        ax3.plot(times, humids, label='Vlhkosti (%)')
        fig.legend(loc='upper left')
        ax.set_xlabel('Čas (h)')
        buf = io.BytesIO()
        fig.savefig(buf)
        pywebio.output.put_image(buf.getvalue())

        fig2.legend(loc='upper left')
        ax2.set_xlabel('Čas (h)')
        buf2 = io.BytesIO()
        fig2.savefig(buf2)
        pywebio.output.put_image(buf2.getvalue())

        fig3.legend(loc='upper left')
        ax3.set_xlabel('Čas (h)')
        buf3 = io.BytesIO()
        fig3.savefig(buf3)
        pywebio.output.put_image(buf3.getvalue())
    else:
        fig, ax = plt.subplots()
        fig2, ax2 = plt.subplots()
        fig3, ax3 = plt.subplots()
        ax.plot(times, temps, label="Teplota (C)")
        ax.plot(times, feel_temps, label='Pocitová teplota (C)')
        ax2.plot(times, pressures, label='Tlak (hPa)')
        ax3.plot(times, humids, label='Vlhkosti (%)')
        fig.legend(loc='upper left')
        ax.set_xlabel('Čas (h)')
        buf = io.BytesIO()
        fig.savefig(buf)
        pywebio.output.put_image(buf.getvalue())

        fig2.legend(loc='upper left')
        ax2.set_xlabel('Čas (h)')
        buf2 = io.BytesIO()
        fig2.savefig(buf2)
        pywebio.output.put_image(buf2.getvalue())

        fig3.legend(loc='upper left')
        ax3.set_xlabel('Čas (h)')
        buf3 = io.BytesIO()
        fig3.savefig(buf3)
        pywebio.output.put_image(buf3.getvalue())
